---
- hosts: servers
  become: yes
  vars:
    __USERHOME__: "/home/{{ ansible_env.SUDO_USER }}"
  roles:
    - { role: ubuntu, when: "ansible_distribution == 'Ubuntu'" }
    - gcc
    - zip
    - wget
    - nmap
    - jq
    - mysql-client
    - sqlite3
    - thunderbird
    - virtualbox
    - vagrant
    - vivaldi
    - tmux
    - software-properties-common

    # depneds on software-properties-common
    - atom
    - dropbox
    - libreoffice
    - git

    # dpends on git
    - gibo
    - nvm
    - pyenv
    - rbenv
