---
keyboard:
  content: |
    # capslock key
    # XKBOPTIONS="ctrl:nocaps" # CapsLock --> Ctrl
    XKBOPTIONS="ctrl:swapcaps" # CapsLock <-> Ctrl

bashrc:
  content: |
    # NVM settings.
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    # PYENV settings.
    export PYENV_ROOT="${HOME}/.pyenv"
    if [ -d "${PYENV_ROOT}" ]; then
      export PATH=${PYENV_ROOT}/bin:$PATH
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    fi

    # RBENV settings.
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
