---
- name: Download git repositories
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    update: yes
  become: "{{ item.value.become }}"
  with_dict: "{{ packages }}"

- name: Download plugin git repositories
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    update: yes
  with_dict: "{{ plugin_packages }}"

- name: Make a link
  file:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    state: link
  become: "{{ item.value.become }}"
  with_dict: "{{ link }}"
