---
- name: Download git repositories
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    update: yes
  become: "{{ item.value.become }}"
  with_dict: "{{ packages }}"

- name: Make a link
  file:
    src: "{{ item.value.link.src }}"
    dest: "{{ item.value.link.dest }}"
    state: link
  become: "{{ item.value.link.become }}"
  when: "'link' in item.value"
  with_dict: "{{ packages }}"
