---
- name: Install language-pack and etc.
  apt:
    name: "{{ item }}"
  with_items:
    - "language-pack-ja"
    - "language-pack-gnome-ja"
    - "thunderbird-locale-ja"
    - "fonts-takao"
    - "ibus-mozc"
  become: yes
  register: install_language_pack

- name: Update locale to JP
  command: update-locale LANG="ja_JP.UTF-8"
  become: yes
  when: install_language_pack|changed
