---
- name: Make a reboot reserve
  command: echo "This notify is executed at first when all tasks finished."
  notify:
    - Reboot server

- import_tasks: mirror.yml
- import_tasks: apt.yml
- import_tasks: language.yml
- import_tasks: localtime.yml
- import_tasks: home-dir.yml
- import_tasks: keyboard.yml
