---
- name: Insatall resolvconf
  apt:
    name: resolvconf
    update_cache: yes
  become: yes

- name: Add DNS address
  lineinfile:
    dest: "/etc/resolvconf/resolv.conf.d/base"
    line: "nameserver 8.8.8.8"
  become: yes
  register: add_DNS_address

- name: Reboot server
  command: shutdown -r now
  become: yes
  when: add_DNS_address|change

- name: Change mirror
  replace:
    dest: "/etc/apt/sources.list"
    regexp: http://(jp\.)?archive\.ubuntu\.com/ubuntu
    replace: http://ftp.riken.go.jp/Linux/ubuntu
  become: yes

- name: Update localtime to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
  become: yes

- name: Install language-pack and etc.
  apt:
    name: "{{ item }}"
  with_items:
    - "language-pack-ja"
    - "language-pack-gnome-ja"
    - "thunderbird-locale-ja"
    - "fonts-takao"
    - "ibus-mozc"
  become: yes

- name: create locale ja_JP.UTF-8
  locale_gen:
    name: ja_JP.UTF-8

- name: set locale to ja_JP.UTF-8
  command: update-locale LANG=ja_JP.UTF-8
  become: yes

- name: Install xdg-user-dirs-gtk
  apt:
    name: "xdg-user-dirs-gtk"
  become: yes

- name: Change home dirs
  command: LANG=C xdg-user-dirs-update --force

- name: Change keyboard settings
  blockinfile:
    dest: "/etc/default/keyboard"
    block: |
      {{ keyboard.content }}
  become: yes
  register: change_keyboard

- name: Enable keyboard setting
  command: dpkg-reconfigure -phigh console-setup
  become: yes
  when: change_keyboard|change

- name: Change .bashrc
  blockinfile:
    dest: "{{ homedir }}/.bashrc"
    block: |
      {{ bashrc.content }}

- name: Place .tmux.conf
  copy:
    src: ".tmux.conf"
    dest: "{{ homedir }}/.tmux.conf"
    mode: 0744
