---
- name: Change mirror
  replace:
    dest: "/etc/apt/sources.list"
    regexp: http://(archive|security)\.ubuntu\.com/ubuntu(.+)
    replace: http://ftp.riken.go.jp/Linux/ubuntu\2
  become: yes
  register: apt_mirror
