---
- name: Install docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - lsb
    - linux-image-extra-virtual
    - linux-image-extra-{{ ansible_kernel }}

- name: Download docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

# 2017-10-22 docker-ce artful 未対応
- name: Define lsb_release
  shell: lsb_release -cs | sed -e s/artful/zesty/
  register: lsb

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb.stdout }} stable"
    state: present
  become: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  become: yes
  notify: Restart docker

- name: Create docker group
  group:
    name: docker
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.17.0-rc1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: "/usr/local/bin/docker-compose"
    mode: 0555
  become: yes
